### ISSUE TITLE
如果artifactId中有下划线会导致创建的数据库名包含下划线导致失败

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone-Plugins#20]
java -jar create-lealone-app-5.0.0.jar -groupId com.ees -artifactId ees-demo-admin
![image](https://user-images.githubusercontent.com/4516585/197373280-ea4354a0-0076-4729-af5c-bab92f720300.png)

如果artifactId中有下划线会导致创建的数据库名包含下划线导致失败

**Comment by codefollower** [comment]
问题修复了，感谢报告问题。
