### ISSUE TITLE
Lealone-Plugins里面test模块打开java类maven加载不了

### ISSUE THREAD

**Issue by tangzhongshan** [lealone/Lealone-Plugins#23]
Lealone-Plugins里面test模块打开java类maven加载不了
[https://github.com/tangzhongshan/tzs/blob/main/1.png](url)

**Comment by codefollower** [comment]
这个是有问题，因为 lealone-test 的 jar 包没有完整部署到 maven 仓库，你把 lealone 的项目导入到 ide 里，然后在 lealone plugins test 模块那里右击菜单，把 lealone-test 手工加入依赖就可以了。

**Comment by codefollower** [comment]
问题已经修复，下载 [Lealone](https://github.com/lealone/Lealone) 的源代码，
然后执行 mvn install -DskipTests 会在本地 maven 仓库中生成一个 lealone-test-5.1.1-SNAPSHOT-tests.jar 文件，
最后更新一下 Lealone-Plugins 的代码就能引用到 lealone-test 模块的类了。
