### ISSUE TITLE
Hive Schema Tool 以 dbtype  mysql 连接遇到错误

### ISSUE THREAD

**Issue by mervynzhang** [lealone/Lealone-Plugins#24]
CREATE TABLE IF NOT EXISTS `BUCKETING_COLS` ( `SD_ID` bigint(20) NOT NULL, `BUCKET_COL_NAME` varchar(256) **CHARACTER SET latin1 COLLATE latin1_bin** DEFAULT NULL, `INTEGER_IDX` int(11) NOT NULL, PRIMARY KEY (`SD_ID`,`INTEGER_IDX`), KEY `BUCKETING_COLS_N49` (`SD_ID`), CONSTRAINT `BUCKETING_COLS_FK1` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`) ) **ENGINE=InnoDB DEFAULT CHARSET=latin1**

SQL Error [42001] [HY000]: Syntax error in SQL statement "                                                              CREATE TABLE IF NOT EXISTS ""BUCKETING_COLS"" ( ""SD_ID"" BIGINT(20) NOT NULL, ""BUCKET_COL_NAME"" VARCHAR(256)  COLLATE[*] LATIN1_BIN DEFAULT NULL, ""INTEGER_IDX"" INT(11) NOT NULL, PRIMARY KEY (""SD_ID"",""INTEGER_IDX""), KEY ""BUCKETING_COLS_N49"" (""SD_ID""), CONSTRAINT ""BUCKETING_COLS_FK1"" FOREIGN KEY (""SD_ID"") REFERENCES ""SDS"" (""SD_ID"") ) "; expected "FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )" [42001-0]

**Comment by codefollower** [comment]
出现 Syntax error in SQL statement 这样的错误就代表 Lealone 的 MySQL 插件还不支持 MySQL 的某种语法。
