### ISSUE TITLE
dbeaver 以 postgres 连的话，  ERROR: Function "FORMAT_TYPE" not found

### ISSUE THREAD

**Issue by mervynzhang** [lealone/Lealone-Plugins#25]
ERROR: Function "FORMAT_TYPE" not found; SQL statement:
SELECT t.oid,t.*,c.relkind,format_type(nullif(t.typbasetype, 0), t.typtypmod) as base_type_name, d.description
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_class c ON c.oid=t.typrelid
LEFT OUTER JOIN pg_catalog.pg_description d ON t.oid=d.objoid
WHERE t.typname IS NOT NULL
AND (c.relkind IS NULL OR c.relkind = 'c') [90022-0]
  Detail: org.lealone.common.exceptions.JdbcSQLException: Function "FORMAT_TYPE" not found; SQL statement:
SELECT t.oid,t.*,c.relkind,format_type(nullif(t.typbasetype, 0), t.typtypmod) as base_type_name, d.description
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_class c ON c.oid=t.typrelid
LEFT OUTER JOIN pg_catalog.pg_description d ON t.oid=d.objoid
WHERE t.typname IS NOT NULL
AND (c.relkind IS NULL OR c.relkind = 'c') [90022-0]

**Comment by mervynzhang** [comment]
psycopg2 也会报以下错误

ProgrammingError                          Traceback (most recent call last)
<ipython-input-32-5a9b0a30a26a> in <module>
----> 1 cursor.execute('SET SESSION[*] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;')

ProgrammingError: Syntax error in SQL statement "**SET SESSION[*][*]** CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED"; expected "@, AUTOCOMMIT, PASSWORD, SALT, SCHEMA, SCHEMA_SEARCH_PATH, ALLOW_LITERALS, COLLATION, BINARY_COLLATION, LOB_COMPRESSION_ALGORITHM, DATABASE_EVENT_LISTENER, DEFAULT_TABLE_TYPE, MODE, STATEMENT_TIMEOUT, CLIENT_ENCODING, CLIENT_MIN_MESSAGES, JOIN_COLLAPSE_LIMIT, DATESTYLE, SEARCH_PATH"; SQL statement:
SET SESSION[*] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED [42001-0]
DETAIL:  org.lealone.common.exceptions.JdbcSQLException: Syntax error in SQL statement "SET SESSION[*][*] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED"; expected "@, AUTOCOMMIT, PASSWORD, SALT, SCHEMA, SCHEMA_SEARCH_PATH, ALLOW_LITERALS, COLLATION, BINARY_COLLATION, LOB_COMPRESSION_ALGORITHM, DATABASE_EVENT_LISTENER, DEFAULT_TABLE_TYPE, MODE, STATEMENT_TIMEOUT, CLIENT_ENCODING, CLIENT_MIN_MESSAGES, JOIN_COLLAPSE_LIMIT, DATESTYLE, SEARCH_PATH"; SQL statement:
SET SESSION[*] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED [42001-0]

**Comment by codefollower** [comment]
出现 Syntax error in SQL statement 这样的错误就代表 Lealone 的 PostgreSQL 插件还不支持 PostgreSQL 的某种语法。

**Comment by codefollower** [comment]
https://github.com/qinsql/QinSQL/pull/29
